version: 2

linters:
  default: all
  disable:
    - wsl
    - depguard
    - err113
    - exhaustruct
    - revive
    - varnamelen
    - funlen
    - tagliatelle
    - wrapcheck
    - mnd
    - gochecknoglobals
